export const CLASS_LEVELS = [
  'GRADE1','GRADE2','GRADE3','GRADE4','GRADE5','GRADE6',
  'GRADE7','GRADE8','GRADE9','GRADE10','GRADE11','GRADE12',
  'UTBK'
];

export const CURRICULA = ['MERDEKA','K13_REVISI'];
